//! Diesel schema for the SQLite backing store.

// @generated by diesel-cli, manually maintained for this project.

diesel::table! {
    config (network_name) {
        network_name -> Text,
        rest -> Text,
        sse -> Text,
        rpc -> Text,
        binary -> Text,
        gossip -> Text,
    }
}

diesel::table! {
    network (network_name) {
        network_name -> Text,
        chain_name -> Text,
    }
}

diesel::joinable!(config -> network (network_name));

diesel::allow_tables_to_appear_in_same_query!(config, network,);
